achivements/urls.py
from django.urls import path

from .views import *


#awards
urlpatterns = [
    path('detail/award/<int:pid>/', AwardDetailView.as_view(), name='award-detail'),
    path('create/award/', AwardCreateView.as_view(), name='award-create'),
    path('update/award/<int:pid>/', AwardUpdateView.as_view(), name='award-update'),
    path('delete/award/<int:pid>/', AwardDeleteView.as_view(), name='award-delete'),
    path('filter/award/<int:year>/', filter_awards,name='award-filter'),
]

#Conference
urlpatterns += [
    path('detail/conference/<int:cid>/',
         ConferenceDetailView.as_view(), name='conference-detail'),
    path('create/conference/', ConferenceCreateView.as_view(),
         name='conference-create'),
    path('update/conference/<int:cid>/',
         ConferenceUpdateView.as_view(), name='conference-update'),
    path('delete/conference/<int:cid>/',
         ConferenceDeleteView.as_view(), name='conference-delete'),
     path('filter/conference/<int:year>', filter_conferences, name='conference-filter'),
]

#journal
urlpatterns += [
    path('detail/journal/<int:pid>/',
         JournalDetailView.as_view(), name='journal-detail'),
    path('create/journal/', JournalCreateView.as_view(),
         name='journal-create'),
    path('update/journal/<int:pid>/',
         JournalUpdateView.as_view(), name='journal-update'),
    path('delete/journal/<int:pid>/',
         JournalDeleteView.as_view(), name='journal-delete'),
    path('filter/journal/<int:year>',
         filter_journals, name='journal-filter'),
]

#workshop
urlpatterns += [
    path('detail/workshop/<int:pid>/',
         WorkshopDetailView.as_view(), name='workshop-detail'),
    path('create/workshop/', WorkshopCreateView.as_view(),
         name='workshop-create'),
    path('update/workshop/<int:pid>/',
         WorkshopUpdateView.as_view(), name='workshop-update'),
    path('delete/workshop/<int:pid>/',
         WorkshopDeleteView.as_view(), name='workshop-delete'),
    path('filter/workshop/<int:year>',
         filter_workshops, name='workshop-filter'),
]

facultyAchivementForum/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from django.conf.urls.static import static
from django.conf import settings

from  users.views import change_password
from .views import index, achivement_index

urlpatterns = [
    path('',index,name='index'),
    path('achivement_show/<int:pk>/', achivement_index, name='achivement-index'),
    path('admin/', admin.site.urls),
    path('users/password', change_password, name='change_password'),
    path('users/',include('django.contrib.auth.urls')),
    path('faculty/',include('users.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from django.contrib import auth
from . import views

urlpatterns = [
    path('',views.welcome_faculty,name='teacher-home'),
    path('<int:pk>/profile', views.teacher_profile, name='teacher-profile'),
    path('create/',views.TeacherCreate.as_view(),name='teacher-create'),
    path('<int:pk>/update/',views.TeacherUpdateView.as_view(),name='teacher-update'),
]

urlpatterns += [
    path('<int:pk>/achivements/', include('achivements.urls'))
]

achivements/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings

import time

from users.models import Teacher

# Create your models here.

def file_award(instance,filename):
    return 'user_{0}/award/{2}_{1}'.format(instance.fid.id,filename,time.time())

def file_conference(instance,filename):
    return 'user_{0}/conference/{2}_{1}'.format(instance.fid.id, filename, time.time())

def file_journal(instance, filename):
    return 'user_{0}/journal/{2}_{1}'.format(instance.fid.id, filename, time.time())

def file_workshop(instance, filename):
    return 'user_{0}/workshop/{2}_{1}'.format(instance.fid.id, filename, time.time())

class Award(models.Model):
    pid = models.AutoField(primary_key=True)
    award_title = models.CharField(help_text="Title Of Award",max_length=200)
    award_date = models.DateField(verbose_name="Awarded On",null=True,blank=True)
    award_details = models.TextField(null=True,blank=False)
    certificate = models.FileField(upload_to=file_award,null=True,blank=True)
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.award_title
    
    def get_absolute_url(self):
        return reverse('award-detail',args=[self.fid.id,self.pid])
    
    class Meta:
        ordering = ['award_date','award_title']


TYPE_CHOICE = (
    ('N', 'National'),
    ('IN', 'International'),
    ('IEEE-N', 'IEEE-National'),
    ('IEEE-IN', 'IEEE-International')
)

class Conference(models.Model):
    #pid = models.IntegerField(primary_key=True,editable=False)
    pid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, help_text="Conference Name")
    title = models.CharField(max_length=200, help_text="Enter Title")
    date = models.DateField(verbose_name="Date of Conference",blank=True,null=True)
    TYPE_CHOICE = (
        ('N','National'),
        ('IN','International'),
        ('IEEE-N','IEEE-National'),
        ('IEEE-IN','IEEE-International')
    )
    certificate = models.FileField(upload_to=file_conference, null=True, blank=True)
    conference_type = models.CharField(choices=TYPE_CHOICE,max_length=20,default='N')
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('conference-detail', args=[self.fid.id, self.pid])

    def conference_type_verbose(self):
        return dict(TYPE_CHOICE)[self.conference_type]

    class Meta:
        ordering = ['date','name','title']
    
class Journal(models.Model):
    pid = models.AutoField(primary_key=True)
    journal_title = models.CharField(verbose_name="Title of Journal",max_length=200)
    paper_title = models.CharField(verbose_name="Title of Paper", max_length=200)
    date = models.DateField(verbose_name="Journal Presentation Date",blank=True,null=False)
    journal_type = models.CharField(
        max_length=20, choices=TYPE_CHOICE, default='N')
    impact_factor = models.FloatField(blank=True,null=True)
    certificate = models.FileField(upload_to=file_journal, null=True, blank=True)
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.journal_title
    
    def get_absolute_url(self):
        return reverse('journal-detail', args=[self.fid.id, self.pid])
    
    def journal_type_verbose(self):
        return dict(TYPE_CHOICE)[self.journal_type]
    
    class Meta:
        ordering = ['date','journal_title', 'paper_title']

class Workshop(models.Model):
    pid = models.AutoField(primary_key=True)
    topic = models.CharField(max_length=200,verbose_name="Workshop Title")
    date = models.DateField(verbose_name="Held on",blank=True,null=True)
    workshop_type = models.CharField(
        choices=TYPE_CHOICE, max_length=20, default='N')
    location = models.CharField(verbose_name="Held at(location)",max_length=200)
    certificate = models.FileField(upload_to=file_workshop, null=True, blank=True)
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.topic
    
    def get_absolute_url(self):
        return reverse('workshop-detail', args=[self.fid.id, self.pid])
    
    def workshop_type_verbose(self):
        return dict(TYPE_CHOICE)[self.workshop_type]
    
    class Meta:
        ordering = ['date', 'topic']

achivements/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, UpdateView, DeleteView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
# Create your views here.

from .models import Award, Journal, Conference, Workshop
from .forms import AwardForm, ConferenceForm, JournalForm, WorkshopForm
from users.models import Teacher


LOGIN_URL = reverse_lazy('login')


class AwardDetailView(DetailView):
    model = Award
    pk_url_kwarg = 'pid'


class AwardCreateView(LoginRequiredMixin, CreateView):
    model = Award
    form_class = AwardForm
    login_url = LOGIN_URL
    success_url = reverse_lazy('teacher-home')

    # def get(self,request,*args,**kwargs):
    #     context = {'form':AwardForm(initial={'fid':request.user.id})}
    #     return render(request,'achivements/award_form.html',context=context)
    def get_initial(self, *args, **kwargs):
        initial = super(AwardCreateView, self).get_initial(**kwargs)
        initial['fid'] = self.request.user.id
        return initial

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AwardCreateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "Award Successfully Created")
        return super().form_valid(form)


class AwardUpdateView(LoginRequiredMixin, UpdateView):
    model = Award
    form_class = AwardForm
    #fields = ('award_title','award_date','award_details','certificate')
    login_url = LOGIN_URL
    pk_url_kwarg = 'pid'
    template_name = 'achivements/award_update_form.html'
    success_url = reverse_lazy('teacher-home')

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(AwardUpdateView, self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
            self.object = form.save()
            messages.success(self.request, "Award Successfully Updated")
            return super().form_valid(form)


class AwardDeleteView(LoginRequiredMixin, DeleteView):
    model = Award
    pk_url_kwarg = 'pid'
    success_url = reverse_lazy('teacher-home')
    login_url = LOGIN_URL

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(request, "Award Successfully deleted")
        return HttpResponseRedirect(success_url)


class ConferenceDetailView(DetailView):
    model = Conference
    pk_url_kwarg = 'cid'


class ConferenceCreateView(LoginRequiredMixin, CreateView):
    model = Conference
    form_class = ConferenceForm
    login_url = LOGIN_URL
    success_url = reverse_lazy('teacher-home')

    def get_initial(self, *args, **kwargs):
        initial = super(ConferenceCreateView, self).get_initial(**kwargs)
        initial['fid'] = self.request.user.id
        return initial

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(ConferenceCreateView,
                       self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "Conference Successfully Created")
        return super().form_valid(form)


class ConferenceUpdateView(LoginRequiredMixin, UpdateView):
    model = Conference
    form_class = ConferenceForm
    login_url = LOGIN_URL
    pk_url_kwarg = 'cid'
    template_name = 'achivements/conference_update_form.html'
    success_url = reverse_lazy('teacher-home')

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(ConferenceUpdateView,
                       self).get_form_kwargs(*args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "Conference Successfully Updated")
        return super().form_valid(form)


class ConferenceDeleteView(LoginRequiredMixin, DeleteView):
    model = Conference
    pk_url_kwarg = 'cid'
    success_url = reverse_lazy('teacher-home')
    login_url = LOGIN_URL

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(request, "Conference Successfully deleted")
        return HttpResponseRedirect(success_url)



class JournalDetailView(DetailView):
    model = Journal
    pk_url_kwarg = 'pid'


class JournalCreateView(LoginRequiredMixin, CreateView):
    model = Journal
    form_class = JournalForm
    login_url = LOGIN_URL
    success_url = reverse_lazy('teacher-home')

    def get_initial(self, *args, **kwargs):
        initial = super(JournalCreateView, self).get_initial(**kwargs)
        initial['fid'] = self.request.user.id
        return initial

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(JournalCreateView, self).get_form_kwargs(
            *args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "Journal Successfully Created")
        return super().form_valid(form)


class JournalUpdateView(LoginRequiredMixin, UpdateView):
    model = Journal
    pk_url_kwarg = 'pid'
    success_url = reverse_lazy('teacher-home')
    template_name = 'achivements/journal_update_form.html'
    form_class = JournalForm

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(JournalUpdateView, self).get_form_kwargs(
            *args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "Journal Successfully Updated")
        return super().form_valid(form)


class JournalDeleteView(LoginRequiredMixin, DeleteView):
    model = Journal
    pk_url_kwarg = 'pid'
    success_url = reverse_lazy('teacher-home')
    login_url = LOGIN_URL

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(request, "Journal Successfully deleted")
        return HttpResponseRedirect(success_url)


class WorkshopDetailView(DetailView):
    model = Workshop
    pk_url_kwarg = 'pid'


class WorkshopCreateView(LoginRequiredMixin, CreateView):
    model = Workshop
    form_class = WorkshopForm
    login_url = LOGIN_URL
    success_url = reverse_lazy('teacher-home')

    def get_initial(self, *args, **kwargs):
        initial = super(WorkshopCreateView, self).get_initial(**kwargs)
        initial['fid'] = self.request.user.id
        return initial

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(WorkshopCreateView, self).get_form_kwargs(
            *args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        self.object = form.save()
        messages.success(self.request, "Workshop Successfully Created")
        return super().form_valid(form)


class WorkshopUpdateView(LoginRequiredMixin, UpdateView):
    model = Workshop
    pk_url_kwarg = 'pid'
    success_url = reverse_lazy('teacher-home')
    login_url = LOGIN_URL
    template_name = 'achivements/workshop_update_form.html'
    form_class = WorkshopForm

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super(WorkshopUpdateView, self).get_form_kwargs(
            *args, **kwargs)
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
            self.object = form.save()
            messages.success(self.request, "Workshop Successfully Updated")
            return super().form_valid(form)


class WorkshopDeleteView(LoginRequiredMixin, DeleteView):
    model = Workshop
    pk_url_kwarg = 'pid'
    success_url = reverse_lazy('teacher-home')
    login_url = LOGIN_URL

    def delete(self, request, *args, **kwargs):
        """
        Call the delete() method on the fetched object and then redirect to the
        success URL.
        """
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(request, "Workshop Successfully deleted")
        return HttpResponseRedirect(success_url)




#filter
def filter_awards(request, pk, year):
    awards = Award.objects.filter(
        award_date__year=year, fid__id=pk)
    context = {
        'awards': awards,
        'year': year,
        'faculty': Teacher.objects.get(id=pk)
    }
    return render(request, 'achivements/award_year.html', context=context)


def filter_conferences(request, pk, year):
    conference = Conference.objects.filter(
        date__year=year, fid__id=pk)
    context = {
        'conferences': conference,
        'year': year,
        'faculty': Teacher.objects.get(id=pk)
    }
    return render(request, 'achivements/conference_year.html', context=context)


def filter_journals(request, pk, year):
    journal = Journal.objects.filter(
        date__year=year, fid__id=pk)
    context = {
        'journals': journal,
        'year': year,
        'faculty': Teacher.objects.get(id=pk)
    }
    return render(request, 'achivements/journal_year.html', context=context)


def filter_workshops(request, pk, year):
    print(pk)

achivements/templates/achivements/award_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Delete Award</h3>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input class="btn btn-danger" type="Submit" value="Confirm">
    <a href="{% url 'teacher-home' %}"><input class="btn btn-primary" type="button" value="Cancle"></a>
</form>
{% endblock %}

achivements/templates/achivements/award_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Award Details: </h3>
<p><b>Award Title: </b>{{award.award_title}}</p>
<p><b>Date Awarded: </b>{{award.award_date}}</p>
<p><b>Detail: </b>{{award.award_details}}</p>
{% if award.certificate %}
<p><b>Certificates: </b><a href="{{award.certificate.url}}" target="_blank">Open</a></p>
{% endif %}
{% endblock %}

achivements/templates/achivements/award_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Create new Award</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Create" class="btn btn-primary">
            <input type="reset" value="Reset" class="btn btn-danger">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $("#id_award_date").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
</script>
{% endblock %}

achivements/templates/achivements/award_update_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Update Award</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Update" class="btn btn-primary">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $("#id_award_date").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
</script>
{% endblock %}

achivements/templates/achivements/award_year.html
{% extends "base_generic.html" %}
{% block content %}
{% if not user.is_authenticated %}
<h1>{{faculty}}</h1>
{% endif %}
<h1>Award(s) in year: {{year}}</h1>
{% for award in awards %}
<div class="jumbotron">
    <p><b>Award Title: </b>{{award.award_title}}</p>
    <p><b>Date Awarded: </b>{{award.award_date}}</p>
    <p><b>Detail: </b>{{award.award_details}}</p>
    {% if award.certificate %}
    <p><b>Certificates: </b><a href="{{award.certificate.url}}" target="_blank">Open</a></p>
    {% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'award-update' user.id award.pid %}"><button class="btn btn-primary">Edit</button></a>
    <a href="{% url 'award-delete' user.id award.pid %}"><button class="btn btn-danger">Delete</button></a>
    {% endif %}
</div>
{% endfor %}
{% endblock %}

achivements/templates/achivements/conference_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Conference Details: </h3>
<p><b>Conference Name: </b>{{conference.name}}</p>
<p><b>Paper Title: </b>{{conference.title}}</p>
<p><b>Conference Date: </b>{{conference.date}}</p>
<p><b>Type: </b>{{conference.conference_type}}</p>
{% if conference.certificate %}
<p><b>Certificates: </b><a href="{{conference.certificate.url}}">Open</a></p>
{% endif %}
{% endblock %}

achivements/templates/achivements/conference_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Create new Conference</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Create" class="btn btn-primary">
            <input type="reset" value="Reset" class="btn btn-danger">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $("#id_date").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
</script>
{% endblock %}

achivements/templates/achivements/conference_year.html
{% extends "base_generic.html" %}
{% block content %}
{% if not user.is_authenticated %}
<h1>{{faculty}}</h1>
{% endif %}
<h1>Conference(s) in year: {{year}}</h1>
{% for conference in conferences %}
<div class="jumbotron">
    <p><b>Conference Name: </b>{{conference.name}}</p>
    <p><b>Paper Title: </b>{{conference.title}}</p>
    <p><b>Conference Date: </b>{{conference.date}}</p>
    <p><b>Type: </b>{{conference.conference_type}}</p>
    {% if conference.certificate %}
    <p><b>Certificates: </b><a href="{{conference.certificate.url}}">Open</a></p>
    {% endif %}
    {% if user.is_authenticated %}
    <a href="{% url 'conference-update' user.id conference.pid %}"><button class="btn btn-primary">Edit</button></a>
    <a href="{% url 'conference-delete' user.id conference.pid %}"><button class="btn btn-danger">Delete</button></a>
    {% endif %}
</div>
{% endfor %}
{% endblock %}

achivements/templates/achivements/journal_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Delete Journal</h3>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input class="btn btn-danger" type="Submit" value="Confirm">
    <a href="{% url 'teacher-home' %}"><input class="btn btn-primary" type="button" value="Cancle"></a>
</form>
{% endblock %}

achivements/templates/achivements/journal_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Create new Journal</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Create" class="btn btn-primary">
            <input type="reset" value="Reset" class="btn btn-danger">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $("#id_date").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
</script>
{% endblock %}

achivements/templates/achivements/workshop_confirm_delete.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Delete Workshop</h3>
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{object}}"?</p>
    <input class="btn btn-danger" type="Submit" value="Confirm">
    <a href="{% url 'teacher-home' %}"><input class="btn btn-primary" type="button" value="Cancle"></a>
</form>
{% endblock %}

achivements/templates/achivements/workshop_detail.html
{% extends "base_generic.html" %}
{% block content %}
<h3>Workshop Details: </h3>
<p><b>Workshop Topic: </b>{{workshop.topic}}</p>
<p><b>Date: </b>{{workshop.date}}</p>
<p><b>Type: </b>{{workshop.workshop_type}}</p>
<p><b>Location: </b>{{workshop.location}}</p>
{% if workshop.certificate.url %}
<p><b>Certificates: </b><a href="{{workshop.certificate.url}}" target="_blank">Open</a></p>
{% endif %}
{% endblock %}

achivements/templates/achivements/workshop_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Create new Workshop</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Create" class="btn btn-primary">
            <input type="reset" value="Reset" class="btn btn-danger">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $("#id_date").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
</script>
{% endblock %}

achivements/templates/achivements/workshop_update_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h3>Update Workshop</h3>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <input type="submit" value="Update" class="btn btn-primary">
        </form>
    </div>
    <div class="col-md-2"></div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $("#id_date").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
</script>
{% endblock %}