facultyAchivementForum/urls.py
from django.contrib import admin
from django.urls import path,include,re_path

from django.conf.urls.static import static
from django.conf import settings

from  users.views import change_password
from .views import index, achivement_index

urlpatterns = [
    path('',index,name='index'),
    path('achivement_show/<int:pk>/', achivement_index, name='achivement-index'),
    path('admin/', admin.site.urls),
    path('users/password', change_password, name='change_password'),
    path('users/',include('django.contrib.auth.urls')),
    path('faculty/',include('users.urls'))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path,include
from django.contrib import auth
from . import views

urlpatterns = [
    path('',views.welcome_faculty,name='teacher-home'),
    path('<int:pk>/profile', views.teacher_profile, name='teacher-profile'),
    path('create/',views.TeacherCreate.as_view(),name='teacher-create'),
    path('<int:pk>/update/',views.TeacherUpdateView.as_view(),name='teacher-update'),
]

urlpatterns += [
    path('<int:pk>/achivements/', include('achivements.urls'))
]

achivements/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings

import time

from users.models import Teacher

# Create your models here.

def file_award(instance,filename):
    return 'user_{0}/award/{2}_{1}'.format(instance.fid.id,filename,time.time())

def file_conference(instance,filename):
    return 'user_{0}/conference/{2}_{1}'.format(instance.fid.id, filename, time.time())

def file_journal(instance, filename):
    return 'user_{0}/journal/{2}_{1}'.format(instance.fid.id, filename, time.time())

def file_workshop(instance, filename):
    return 'user_{0}/workshop/{2}_{1}'.format(instance.fid.id, filename, time.time())

class Award(models.Model):
    pid = models.AutoField(primary_key=True)
    award_title = models.CharField(help_text="Title Of Award",max_length=200)
    award_date = models.DateField(verbose_name="Awarded On",null=True,blank=True)
    award_details = models.TextField(null=True,blank=False)
    certificate = models.FileField(upload_to=file_award,null=True,blank=True)
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.award_title
    
    def get_absolute_url(self):
        return reverse('award-detail',args=[self.fid.id,self.pid])
    
    class Meta:
        ordering = ['award_date','award_title']


TYPE_CHOICE = (
    ('N', 'National'),
    ('IN', 'International'),
    ('IEEE-N', 'IEEE-National'),
    ('IEEE-IN', 'IEEE-International')
)

class Conference(models.Model):
    #pid = models.IntegerField(primary_key=True,editable=False)
    pid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, help_text="Conference Name")
    title = models.CharField(max_length=200, help_text="Enter Title")
    date = models.DateField(verbose_name="Date of Conference",blank=True,null=True)
    TYPE_CHOICE = (
        ('N','National'),
        ('IN','International'),
        ('IEEE-N','IEEE-National'),
        ('IEEE-IN','IEEE-International')
    )
    certificate = models.FileField(upload_to=file_conference, null=True, blank=True)
    conference_type = models.CharField(choices=TYPE_CHOICE,max_length=20,default='N')
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('conference-detail', args=[self.fid.id, self.pid])

    def conference_type_verbose(self):
        return dict(TYPE_CHOICE)[self.conference_type]

    class Meta:
        ordering = ['date','name','title']
    
class Journal(models.Model):
    pid = models.AutoField(primary_key=True)
    journal_title = models.CharField(verbose_name="Title of Journal",max_length=200)
    paper_title = models.CharField(verbose_name="Title of Paper", max_length=200)
    date = models.DateField(verbose_name="Journal Presentation Date",blank=True,null=False)
    journal_type = models.CharField(
        max_length=20, choices=TYPE_CHOICE, default='N')
    impact_factor = models.FloatField(blank=True,null=True)
    certificate = models.FileField(upload_to=file_journal, null=True, blank=True)
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.journal_title
    
    def get_absolute_url(self):
        return reverse('journal-detail', args=[self.fid.id, self.pid])
    
    def journal_type_verbose(self):
        return dict(TYPE_CHOICE)[self.journal_type]
    
    class Meta:
        ordering = ['date','journal_title', 'paper_title']

class Workshop(models.Model):
    pid = models.AutoField(primary_key=True)
    topic = models.CharField(max_length=200,verbose_name="Workshop Title")
    date = models.DateField(verbose_name="Held on",blank=True,null=True)
    workshop_type = models.CharField(
        choices=TYPE_CHOICE, max_length=20, default='N')
    location = models.CharField(verbose_name="Held at(location)",max_length=200)
    certificate = models.FileField(upload_to=file_workshop, null=True, blank=True)
    fid = models.ForeignKey(Teacher,on_delete=models.CASCADE)

    def __str__(self):
        return self.topic
    
    def get_absolute_url(self):
        return reverse('workshop-detail', args=[self.fid.id, self.pid])
    
    def workshop_type_verbose(self):
        return dict(TYPE_CHOICE)[self.workshop_type]
    
    class Meta:
        ordering = ['date', 'topic']

users/models.py
from django.db import models,connection
from django.contrib.auth.models import AbstractUser
import time

from .queries import get_award_year, get_conference_year, get_journal_year, get_workshop_year

# Create your models here.


def file_pic(instance, filename):
    return 'user_{0}/pic/{2}_{1}'.format(instance.id, filename, time.time())


class Department(models.Model):
    department_id = models.IntegerField(primary_key=True)
    department_name = models.CharField(max_length=100)
    hodid = models.ForeignKey('Teacher',on_delete=models.SET_NULL,null=True,related_name='hod')

    def __str__(self):
        return self.department_name


class Teacher(AbstractUser):
    profile_pic = models.ImageField(verbose_name="Profile Picture",blank=True,null=True,upload_to=file_pic,default='default.png')
    middle_name = models.CharField(max_length=30, blank=True, null=True)
    dob = models.DateField(verbose_name='Date Of Birth', null=True)
    doj = models.DateField(verbose_name='Date Of Join', null=True)
    mobile_num = models.CharField(verbose_name='Mobile Number',max_length=10,null=True,blank=True)

    SEX_CHOICE = (
        ('m','Male'),
        ('f','Female'),
        ('t','Transgender'),
        ('o','Others')
    )
    sex = models.CharField(max_length=1,choices=SEX_CHOICE,default='m')
    department = models.ForeignKey('Department',on_delete=models.SET_NULL,null=True)
    """
    @property
    def is_hod(self):
        if self.department.hodid.id is not None:
            if self.department.hodid.id == self.id:
                return True
        return False
    """
    @property
    def award_years(self):
        return get_award_year(self)
    
    @property
    def conference_years(self):
        return get_conference_year(self)
    
    @property
    def journal_years(self):
        return get_journal_year(self)
    
    @property
    def workshop_years(self):
        return get_workshop_year(self)
    
    
    def __str__(self):
        return self.first_name+' '+self.last_name
    
    def sex_verbose(self):
        return dict(Teacher.SEX_CHOICE)[self.sex]

    

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.exceptions import ValidationError
from django.conf import settings

from .models import Teacher,Department
from django import forms

import datetime


class TeacherCreationForm(UserCreationForm):
    dob = forms.DateField(
        input_formats=settings.DATE_INPUT_FORMATS, required=False)
    doj = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS,required=False)

    # def clean_dob(self):
    #     data = self.cleaned_data['dob']
    #     if(data > datetime.date.today()):
    #         raise ValidationError("Invalid Date of Birth(date in future)")
    
    # def clean_doj(self):
    #     doj_data = self.cleaned_data['doj']
    #     if(doj_data > datetime.date.today()):
    #         raise ValidationError("Invalid Date of Join(date in future)")


    class Meta(UserCreationForm):
        model = Teacher
        fields = ('username', 'email', 'mobile_num', 'first_name',
                  'middle_name', 'last_name', 'dob', 'doj', 'sex', 'department','profile_pic')



class TeacherChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = Teacher
        fields = ('username', 'email', 'mobile_num', 'first_name',
                  'middle_name', 'last_name', 'dob', 'doj', 'sex', 'department','profile_pic')


class DepartmentChoice(forms.Form):
    department = forms.ModelChoiceField(queryset=Department.objects.all())

users/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from .models import Teacher, Department
from .forms import TeacherChangeForm,TeacherCreationForm

# Create your views here.

@login_required(login_url=reverse_lazy('login'))
def welcome_faculty(request):
    return render(request,'users/teacher_home.html')

@login_required(login_url=reverse_lazy('login'))
def teacher_profile(request,pk):
    return render(request,'users/teacher_profile.html')

class TeacherCreate(generic.CreateView):
    model = Teacher
    form_class = TeacherCreationForm
    success_url = reverse_lazy('login')


class TeacherUpdateView(LoginRequiredMixin,generic.UpdateView):
    model = Teacher
    form_class = TeacherChangeForm
    success_url = reverse_lazy('teacher-home')
    login_url = reverse_lazy('login')

@login_required(login_url=reverse_lazy('login'))
def change_password(request):
    if(request.method=='POST'):
        form = PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request,user)
            messages.success(request,'You password changed successfully')
            return redirect('teacher-home')
        else:
            messages.error(request,"Please correct the error")
    else:
        form = PasswordChangeForm(request.user)
    return render(request,'registration/changed_password.html',{'form':form})


#change hod

templates/users/teacher_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h1>Create New Faculty</h1>
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="submit" class="btn btn-primary">
            </form>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    $(function () {
        $("#id_dob").datepicker({
            format: 'yyyy-mm-dd',
        });
    });
    $(function () {
            $("#id_doj").datepicker({
                format: 'yyyy-mm-dd',
            });
        });
</script>
{% endblock %}

templates/users/teacher_home.html
{% extends "base_generic.html" %}

{% block style %}
<style>
    .tab {
        overflow: hidden;
        border: 1px solid #ccc;
        background-color: #f1f1f1;
    }

    /* Style the buttons that are used to open the tab content */
    .tab button {
        background-color: inherit;
        float: left;
        border: none;
        outline: none;
        cursor: pointer;
        padding: 14px 16px;
        transition: 0.3s;
    }

    /* Change background color of buttons on hover */
    .tab button:hover {
        background-color: #ddd;
    }

    /* Create an active/current tablink class */
    .tab button.active {
        background-color: #ccc;
    }

    /* Style the tab content */
    .tabcontent {
        display: none;
        padding: 6px 12px;
        border: 1px solid #ccc;
        border-top: none;
    }
</style>
{% endblock %}

{% block content %}
<h1 style="align-items: center;">My Achivements</h1>

<div class="tab">
    <button class="tablinks" id="defaultOpen" onclick="openAchivement(event, 'Award')">Awards</button>
    <button class="tablinks" onclick="openAchivement(event, 'Conference')">Conference</button>
    <button class="tablinks" onclick="openAchivement(event, 'Journal')">Journal</button>
    <button class="tablinks" onclick="openAchivement(event, 'Workshop')">Workshop</button>
</div>

<div id="Award" class="tabcontent">
    {% if user.award_set.all %}
    <table border="0">
        {% for award in user.award_set.all %}
        <tr>
            <!-- <td>{{award.award_title}}</td>
            <td><a href="{% url 'award-detail' user.id award.pid %}"><button class="btn btn-primary">Show</button></a>
            </td> -->
            <div class="jumbotron">
                <p><b>Award Title: </b>{{award.award_title}}</p>
                <p><b>Date Awarded: </b>{{award.award_date}}</p>
                <p><b>Detail: </b>{{award.award_details}}</p>
                {% if award.certificate %}
                <p><b>Certificates: </b><a href="{{award.certificate.url}}" target="_blank">Open</a></p>
                {% endif %}
                <a href="{% url 'award-update' user.id award.pid %}"><button class="btn btn-primary">Edit</button></a>
                <a href="{% url 'award-delete' user.id award.pid %}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No Awards Available</p>
    {% endif %}
</div>

<div id="Conference" class="tabcontent">
    {% if user.conference_set.all %}
    <table border="0">
        {% for conference in user.conference_set.all %}
        <tr>
            <div class="jumbotron">
                <p><b>Conference Name: </b>{{conference.name}}</p>
                <p><b>Paper Title: </b>{{conference.title}}</p>
                <p><b>Conference Date: </b>{{conference.date}}</p>
                <p><b>Type: </b>{{conference.conference_type_verbose}}</p>
                {% if conference.certificate %}
                <p><b>Certificates: </b><a href="{{conference.certificate.url}}">Open</a></p>
                {% endif %}
                <a href="{% url 'conference-update' user.id conference.pid %}"><button class="btn btn-primary">Edit</button></a>
                <a href="{% url 'conference-delete' user.id conference.pid %}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No Conference Available</p>
    {% endif %}
</div>

<div id="Journal" class="tabcontent">
    {% if user.journal_set.all %}
    <table border="0">
        {% for journal in user.journal_set.all %}
        <tr>
            <div class="jumbotron">
                <p><b>Journal Title: </b>{{journal.journal_title}}</p>
                <p><b>Paper Title: </b>{{journal.journal_title}}</p>
                <p><b>Date: </b>{{journal.date}}</p>
                <p><b>Type: </b>{{journal.journal_type_verbose}}</p>
                <p><b>Impact Factor: </b>{{journal.impact_factor}}</p>
                {% if journal.certificate %}
                <p><b>Certificates: </b><a href="{{journal.certificate.url}}" target="_blank">Open</a></p>
                {% endif %}
                <a href="{% url 'journal-update' user.id journal.pid %}"><button class="btn btn-primary">Edit</button></a>
                <a href="{% url 'journal-delete' user.id journal.pid %}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No Journal Available</p>
    {% endif %}
</div>

<div id="Workshop" class="tabcontent">
    {% if user.workshop_set.all %}
    <table border="0">
        {% for workshop in user.workshop_set.all %}
        <tr>
            <div class="jumbotron">
                <p><b>Workshop Topic: </b>{{workshop.topic}}</p>
                <p><b>Date: </b>{{workshop.date}}</p>
                <p><b>Type: </b>{{workshop.workshop_type_verbose}}</p>
                <p><b>Location: </b>{{workshop.location}}</p>
                {% if workshop.certificate %}
                <p><b>Certificates: </b><a href="{{workshop.certificate.url}}" target="_blank">Open</a></p>
                {% endif %}
                <a href="{% url 'workshop-update' user.id workshop.pid %}"><button class="btn btn-primary">Edit</button></a>
                <a href="{% url 'workshop-delete' user.id workshop.pid %}"><button class="btn btn-danger">Delete</button></a>
            </div>
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>No Awards Available</p>
    {% endif %}
</div>
{% endblock %}

{% block script %}
<script>
    document.getElementById("defaultOpen").click();
    function openAchivement(evt, Achivement) {
        // Declare all variables
        var i, tabcontent, tablinks;

        // Get all elements with class="tabcontent" and hide them
        tabcontent = document.getElementsByClassName("tabcontent");
        for (i = 0; i < tabcontent.length; i++) {
            tabcontent[i].style.display = "none";
        }

        // Get all elements with class="tablinks" and remove the class "active"
        tablinks = document.getElementsByClassName("tablinks");
        for (i = 0; i < tablinks.length; i++) {
            tablinks[i].className = tablinks[i].className.replace(" active", "");
        }

        // Show the current tab, and add an "active" class to the button that opened the tab
        document.getElementById(Achivement).style.display = "block";
        evt.currentTarget.className += " active";
    }
</script>
{% endblock %}

{% block filters %}
<h3>Filters</h3>
<ul>
    <li>Award
        <ul>
            {% for year in user.award_years %}
            <li><a href="{% url 'award-filter' user.pk year %}">{{year}}</a></li>
            {% endfor %}
        </ul>
    </li>
    <li>Conference
        <ul>
            {% for year in user.conference_years %}
            <li><a href="{% url 'conference-filter' user.pk year %}">{{year}}</a></li>
            {% endfor %}
        </ul>
    </li>
    <li>
        Journal
        <ul>
            {% for year in user.journal_years %}
            <li><a href="{% url 'journal-filter' user.pk year %}">{{year}}</a></li>
            {% endfor %}
        </ul>
    </li>
    <li>
        Workshop
        <ul>
            {% for year in user.workshop_years %}
            <li><a href="{% url 'workshop-filter' user.pk year %}">{{year}}</a></li>
            {% endfor %}
        </ul>
    </li>
</ul>
{% endblock %}

templates/users/teacher_profile.html
{% extends "base_generic.html" %}
{% block content %}
<h2>Profile</h2>
{% if user.profile_pic %}
<img src="{{user.profile_pic.url}}" alt="ops" height="150" width="150">
{% else %}
<img src="https://www.trzcacak.rs/myfile/detail/32-327033_generic-profile-picture-png.png" alt="ops" height="150" width="150">
{% endif %}
<p>Username: {{user.username}}</p>
<p>First Name: {{user.first_name}}</p>
<p>Middle Name: {{user.middle_name}}</p>
<p>last_name: {{user.last_name}}</p>
<p>Email: {{user.email}}</p>
<p>Date Joined: {{user.doj}}</p>
<p>Date of Birth: {{user.dob}}</p>
<p>Mobile Number: {{user.mobile_num}}</p>
<p>Sex: {{user.sex_verbose}}</p>
<p>Department: {{user.department.department_name}}</p>
<p></p>
{% endblock %}